% LFCS  Compute fluorescence autocorrelation using Laurence method on
%   log-spaced data
%
%   [tau, g] = LFCS(filenum,taumin,taumax,N) computes the autocorrelation 
%   curve of the data object 'tags0' inside the file 'data_filenum' in the 
%   current working directory.  tmin and tmax specify lower and upper times
%   (in log10-seconds).  Default is taumin = -6, taumax = -1 (resulting in 
%   the autocorrelation for tau from 1 us to 100 ms.
%
%   N (optional) specifies the number of data points.  Default is 200.
%
%   [tau,g] = LFCS(filenum,taumin,taumax,N,tmin,tmax) allows the
%   specification of starting and stopping times within the data file, so
%   that only points between tmin and tmax will be included in the
%   correlation.
%
%   If there are two data streams inside the file, 'tags0' and 'tags1',
%   then [tau, g] = LFCS(...) will return the cross-correlation of those
%   two streams.
%
%   [tau, g0, g1] = LFCS(...) returns the individual autocorrelations of
%   streams tags0 and tags1.
%
%   [tau, g0, g1, gx] = LFCS(...) also returns the cross-correlation.
%
%   Note that 'tags0' and 'tags1' must be lists of times generated by point 
%   processes.


function [tau,g] = lfcsLL(traces,taumin,taumax,N)

tau = logspace(taumin,taumax,N);
    g = corr_Laurence(traces, traces, tau);
    g = g(1:end-1)-1;

tau = tau(1:end-1);
end
