function  [output, folding] = lifetime40fpsRAW(datasource, concentration)
% a script to break the data into sorted files
% datasource - filename of data
% concentration - the concentration of that datasource
% output concentration | singlefitunfold(k)| doublefitunfold (A1,k1,A2,k2)|
% singlefitfold doublefitfold timetotalhigh totaldwellshigh timetotallow
% totaldwellslow 
% folding (time vs. dwells), unfolding (time vs. dwells)


%first grab the data
A = importdata(datasource);

% then sort it
sorted= sortrows(A,1);

%  find the low/high breakpoint
% low = find(sorted,1) - 1;

% create a low fret array
lowsorted = sorted;
%create the high fret array
% highsorted = sorted(low+1:end,:);

% find the frequency data
    % grab the dwells times into a single array, and divide by the frame rate
% highfretdwells = highsorted(:,2)'/40;
lowfretdwells = lowsorted(:,1)'/40;
   %create a the bin centers vectors from 0 to a value

   
    % get a table of frequency data
%     hightable = tabulatebetter(highfretdwells);
    lowtable = tabulatebetter(lowfretdwells);


longestdwelllow = max(lowtable(:,1));
filler = [0:0.025:longestdwelllow]';
% uniquedwells = unique(hightable(:,1)
for i=1:1:(longestdwelllow*40+1)
    spot = filler(i);
    spotintable = lowtable(i,1);
    if spotintable == spot
      
        continue
    elseif spotintable > spot
    addedrow = [spot 0 lowtable(i-1,3) lowtable(i-1,4)];
    lowtable = [lowtable;addedrow];
    lowtable = sortrows(lowtable,1);
%     next i
%     continue
    end
end
% % % % % % % % % % % % % % % % % % % %     

%total length of dwells
% timetotalhigh = sum(highsorted(:,2))/40;    
timetotallow  = sum(lowsorted(:,1))/40;

%number of dwells
% totaldwellshigh = size(highsorted,1);
totaldwellslow = size(lowsorted,1);

%  Auto-generated by MATLAB on 23-Jun-2005 08:47:11
 title = [num2str(concentration) ' mM Metal kinetics'];
%% Create figure
figure1 = figure('Color',[1 1 1],'Name', title,'PaperPosition',[0.25 0.25 8 10.5]);
 
% % % %% Create axes - High FRET dwells
% % % axes1 = axes('FontName','Arial','FontSize',12,'Position',[0.1 0.1 0.4 0.9],'Parent',figure1);
% % % axes3 = axes('FontName','Arial','FontSize',12,'Position',[0.3 0.1 0.2 0.9],'Parent',figure1,'Visible','on','YAxisLocation','right','YColor','white');
% % % ylim(axes1,[0 1.1]);
% % % ylim(axes3,[0 1.1]);
% % % xlabel(axes1,'Dwell time (s)');
% % % ylabel(axes1,'Normalized counts (cumulative)');
% % % hold(axes1,'all');
% % % hold(axes3,'all');
% % %  
% % % %% Create scatter
% % % scatter1 = scatter(hightable(:,1),hightable(:,4),'Parent',axes1,'Marker','square','MarkerEdgeColor',[0 0 0],'SizeData',[24],'DisplayName','unfoldingfast');
% % % scatter3 = scatter(hightable(:,1),hightable(:,4),'Parent',axes3,'Marker','square','MarkerEdgeColor',[0 0 0],'SizeData',[24],'DisplayName','unfoldingslow');
% % %   
% % % %   fit with single and double exponenetials
% % %                         options = optimset('LevenbergMarquardt','on');
% % %                         doublefithigh = lsqcurvefit(@doubleexponential,[0.6,3,0.1],hightable(:,1),hightable(:,4)); %lsqcurvefit(@function,[GUESSES],xdata,ydata)
% % %                         doublefithighval = [doublefithigh 0];
% % %                         doublefithighval(4) = doublefithigh(3);
% % %                         doublefithighval(3) = (1-doublefithigh(1));
% % %                         singlefithigh = lsqcurvefit(@singleexponential,[1],hightable(:,1),hightable(:,4));
% % %                         xvalues=hightable(:,1);
% % %                         ydouble=(doubleexponential(doublefithigh,xvalues));
% % %                         ysingle=(singleexponential(singlefithigh,xvalues));
% % % %% Create plot double exponential
% % % plot1 = plot(xvalues,ydouble,'Color',[0 0 1],'LineWidth',2,'Parent',axes1,'DisplayName','double exponential');
% % % plot3 = plot(xvalues,ydouble,'Color',[0 0 1],'LineWidth',2,'Parent',axes3,'DisplayName','double exponential');
% % %   
% % % %% Create plot single exponential
% % % plot2 = plot(xvalues,ysingle,'Color',[1 0 0],'LineWidth',2,'Parent',axes1,'DisplayName','single exponential');
% % % plot4 = plot(xvalues,ysingle,'Color',[1 0 0],'LineWidth',2,'Parent',axes3,'DisplayName','single exponential');
% % % 
% % % % Adjust x limits
% % % middley = find ((10*hightable(:,4)') <= 7.5);
% % % middley=max(middley);
% % % 
% % % if middley <= 4
% % %     middley = 4;
% % % end
% % % xaxisbreak = hightable(middley,1);
% % % % set(axes1,'XTick'
% % % xlim(axes1,[0 xaxisbreak]);
% % % xlim(axes3,[xaxisbreak/2 longestdwellhigh+1]);
% % % %adjusts tick marks and labels
% % % currentticks = get(axes3,'XTick');
% % % % currentticks = [currentticks floor(max(hightable(end,1)))];
% % % currentticks(1) = NaN;
% % % betterticks = [xaxisbreak currentticks];
% % % set(axes3,'XTick', betterticks,'XTickLabel', betterticks);
% % % 
% % % % place Break
% % % t1=text(betterticks(1),0,'//','fontsize',15,'HorizontalAlignment','center');
% % % 
% % % %first point ticks
% % % currentticks = get(axes1,'XTick');
% % % betterticks = [currentticks(1);currentticks(2)];
% % % set(axes1,'XTick', betterticks, 'XTickLabel',betterticks);

%% Create axes - Low FRET dwells
axes2 = axes('FontName','Arial','FontSize',12,'Position',[0.59 0.1 0.4 0.9],'Parent',figure1);
axes4 = axes('FontName','Arial','FontSize',12,'Position',[0.78 0.1 0.21 0.9],'Parent',figure1,'Visible','on','YAxisLocation','right','YColor','white');
ylim(axes2,[0 1.1]);
ylim(axes4,[0 1.1]);
xlabel(axes2,'Dwell time (s)');
ylabel(axes2,'Normalized counts (cumulative)');
hold(axes2,'all');
hold(axes4,'all');
 
%% Create scatter
scatter2 = scatter(lowtable(:,1),lowtable(:,4),'Parent',axes2,'Marker','o','SizeData',[24],'MarkerEdgeColor',[0 0 0],'DisplayName','foldingfast');
scatter4 = scatter(lowtable(:,1),lowtable(:,4),'Parent',axes4,'Marker','o','SizeData',[24],'MarkerEdgeColor',[0 0 0],'DisplayName','foldingslow');
 
%   fit with single and double exponenetials
                        options = optimset('LevenbergMarquardt','on','TolFun',0.0000000001);
                        doublefitlow = lsqcurvefit(@doubleexponential,[0.6,3,0.1],lowtable(:,1),lowtable(:,4));
                        doublefitlowval = [doublefitlow 0];
                        doublefitlowval(4) = doublefitlow(3);
                        doublefitlowval(3) = (1-doublefitlow(1));
                        singlefitlow = lsqcurvefit(@singleexponential,[1],lowtable(:,1),lowtable(:,4));
                        xvalues=lowtable(:,1);
                        ydouble=(doubleexponential(doublefitlow,xvalues));
                        ysingle=(singleexponential(singlefitlow,xvalues));
%% Create plot double exponential
plot1 = plot(xvalues,ydouble,'Color',[0 0 1],'LineWidth',2,'Parent',axes2,'DisplayName','double exponential');
plot3 = plot(xvalues,ydouble,'Color',[0 0 1],'LineWidth',2,'Parent',axes4,'DisplayName','double exponential');
 
%% Create plot single exponential
plot2 = plot(xvalues,ysingle,'Color',[1 0 0],'LineWidth',2,'Parent',axes2,'DisplayName','single  exponential');
plot4 = plot(xvalues,ysingle,'Color',[1 0 0],'LineWidth',2,'Parent',axes4,'DisplayName','single  exponential');

%% make it look nice
% Adjust x limits
middley = find ((10*lowtable(:,4)') <= 7.5);
middley=max(middley);

% set(axes1,'XTick'
if middley <= 4
    middley=4;
end
xaxisbreak = lowtable(middley,1);
xlim(axes2,[0 xaxisbreak]);
xlim(axes4,[xaxisbreak/2 longestdwelllow+1]);
%adjusts tick marks and labels
currentticks = get(axes4,'XTick');
% currentticks(end) = floor(max(lowtable(end,1)));
currentticks(1) = NaN;
betterticks = [xaxisbreak currentticks] 
set(axes4,'XTick', betterticks,'XTickLabel', betterticks);

% place Break
t1=text(betterticks(1),0,'//','fontsize',15,'HorizontalAlignment','center');

%first point ticks
currentticks = get(axes2,'XTick');
betterticks = [currentticks(1);currentticks(2)];
set(axes2,'XTick', betterticks, 'XTickLabel',betterticks);


%% Create legend
% legend1 = legend(axes1,{'unfolding','double exponential','single exponential'},'FontName','Arial','FontSize',10,'Position',[0.25 0.15 0.2 0.1]);
 
%% Create legend
legend2 = legend(axes2,{'Cy5 bleaching','double exponential','single exponential'},'FontName','Arial','FontSize',10,'Position',[0.73 0.15 0.2 0.1]);

%create annotation labels
% a = ['k = ' num2str(round(100*singlefithigh)/100)];
% b = ['A1 = ' num2str(round(100*doublefithighval(1))/100)];
% c = ['k1 = ' num2str(round(100*doublefithighval(2))/100)];
% d = ['A2 = ' num2str(round(100*doublefithighval(3))/100)];
% e = ['k2 = ' num2str(round(100*doublefithighval(4))/100)];
% f = [num2str(timetotalhigh) ' s'];
% g = [num2str(totaldwellshigh) ' dwells'];


% %% Create textbox
% annotation1 = annotation(figure1,'textbox','Position',[0.36 0.3 0.1 0.2],'FitHeightToText','on','String',{a,b,c,d,e,});
% annotation3 = annotation(figure1,'textbox','Position',[0.36 0.4 0.1 0.2],'FitHeightToText','on','String',{f,g},'LineStyle','none');
% annotation5 = annotation(figure1,'textbox','Position',[0.15 0.7 0.3 0.3],'String','Unfolding','LineStyle','None','FontSize',18);    

%create annotation labels
a = ['k = ' num2str(round(100*singlefitlow)/100)];
b = ['A1 = ' num2str(round(100*doublefitlowval(1))/100)];
c = ['k1 = ' num2str(round(100*doublefitlowval(2))/100)];
d = ['A2 = ' num2str(round(100*doublefitlowval(3))/100)];
e = ['k2 = ' num2str(round(100*doublefitlowval(4))/100)];
f = [num2str(timetotallow) ' s'];
g = [num2str(totaldwellslow) ' dwells'];

%% Create textbox
annotation2 = annotation(figure1,'textbox','Position',[0.85 0.3 0.1 0.2],'FitHeightToText','on','String',{a,b c,d e});
annotation4 = annotation(figure1,'textbox','Position',[0.85 0.4 0.1 0.2],'FitHeightToText','on','String',{f,g},'LineStyle','none');
annotation6 = annotation(figure1,'textbox','Position',[0.65 0.7 0.3 0.3],'String','Cy5 Photobleaching Rate','FitHeightToText','on','LineStyle','None');  
%output answer

output = [concentration,  singlefitlow doublefitlowval  timetotallow totaldwellslow ];
folding = lowtable;
% unfolding = hightable;


% % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % 
% % OLD CODE
% % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % 

% % %% Create scatter
% % scatter2 = scatter(lowtable(:,1),lowtable(:,4)
% %   'Parent',axes2,...
% %   'DisplayName','b vs. a',...
% %   'XDataSource','a',...
% %   'YDataSource','b');
   
    
% %                             % plot the data
% %                         figure
% %                         scatter(hightable(:,1),hightable(:,4))
% %                         % fit with single and double exponenetials
% %                         options = optimset('LevenbergMarquardt','on');
% %                         doublefithigh = lsqcurvefit(@doubleexponential,[1,3,1,1],hightable(:,1),hightable(:,4));
% %                         singlefithigh = lsqcurvefit(@singleexponential,[1],hightable(:,1),hightable(:,4));
% %                         xvalues=hightable(:,1);
% %                         hold all
% %                         ydouble=(doubleexponential(doublefithigh,xvalues));
% %                         ysingle=(singleexponential(singlefithigh,xvalues));
% %                         plot(xvalues,ydouble)
% %                         plot(xvalues,ysingle)
% %                         %give the axis labels, and graph a title, and a legend, diplay the fits
% % 
% % 
% %                         % plot the data
% %                         figure
% %                         scatter(lowtable(:,1),lowtable(:,4))
% %                         % fit with single and double exponenetials
% %                         options = optimset('LevenbergMarquardt','on');
% %                         doublefitlow = lsqcurvefit(@doubleexponential,[1,3,1,1],lowtable(:,1),lowtable(:,4));
% %                         singlefitlow = lsqcurvefit(@singleexponential,[1],lowtable(:,1),lowtable(:,4));
% %                         xvalues=lowtable(:,1);
% %                         hold all
% %                         ydouble=(doubleexponential(doublefitlow,xvalues));
% %                         ysingle=(singleexponential(singlefitlow,xvalues));
% %                         plot(xvalues,ydouble)
% %                         plot(xvalues,ysingle)
% %                         %give the axis labels, and graph a title, and a legend, diplay the fits
% % 
