function desc=getDefaultDESC()
desc=struct('apd0','APD0','apd1','APD1','apd2','APD2','apd3','APD3',...
    'nidaq0','NIDAQ0','nidaq1','NIDAQ1','nidaq2','NIDAQ2','nidaq3','NIDAQ3',...
    'nidaq4','NIDAQ4','nidaq5','NIDAQ5','nidaq6','NIDAQ6','nidaq7','NIDAQ7',...
    'title','','OD','0',...
    'f1',0,'f1_desc','','f2',0,'f2desc','','f3',0,'f3desc','',...
'comments','');
