function  output = kinanyfps2residuals(datasource,datasource2, concentration, fps)
% a script to break the data into sorted files
% output = kinanyfps2(datasource, concentration, fps)
% datasource - filename of data
% concentration - the concentration of that datasource
% output concentration | singlefitunfold(k)| doublefitunfold (A1,k1,A2,k2)|
% singlefitfold doublefitfold timetotalhigh totaldwellshigh timetotallow
% totaldwellslow 
frame = 1/fps;
if regexpi(datasource, 'refold') ~= 0
    backwards = 1
elseif regexpi(datasource, 'shorten') ~= 0
    backwards = 1
else
    backwards = 0
% regexpi(str, 'c[aeiou]+t')
end

%% Count the number of molecules using datasource2




B = importdata(datasource2);

sortedmolecule= sortrows(B,1);
numbermolecules= find(sortedmolecule(:,1)==9);
numbermolecules= size(numbermolecules,1);
%%

%first grab the data
A = importdata(datasource);

% then sort it
sorted= sortrows(A,1);

%  find the low/high breakpoint
low = find(sorted,1) - 1;

% create a low fret array
lowsorted = sorted(1:low,:);
%create the high fret array
highsorted = sorted(low+1:end,:);

%switch refolding
if backwards == 1
    temp = lowsorted;
    lowsorted = highsorted;
    highsorted = temp;
end


% find the frequency data
    % grab the dwells times into a single array, and divide by the frame rate
highfretdwells = highsorted(:,2)'/fps;
lowfretdwells = lowsorted(:,2)'/fps;
   %create a the bin centers vectors from 0 to a value

   
    % get a table of frequency data
    hightable = tabulatebetter(highfretdwells);
    lowtable = tabulatebetter(lowfretdwells);

% This code fills in dwell time that dont have an observed transition with
% the fraction of events of the earliest real observation
% 120407 This was commented out by Greenfeld, this does not seem to be a
% legit way of processing data


% % % % % % % % % % % % % % % % % % % % 
% fill in the zeros on the table
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

longestdwellhigh = max(hightable(:,1));
%filler = [0:frame:longestdwellhigh]';
% uniquedwells = unique(hightable(:,1)
%for i=1:1:((longestdwellhigh/frame)+1)
%    spot = floor(filler(i)*1000);
%    spotintable = floor(hightable(i,1)*1000);
%    if spotintable == spot  % for some reason, 0.0389 ~= 0.0389!
      
%        continue
%    elseif spotintable > spot
%    addedrow = [filler(i) 0 hightable(i-1,3) hightable(i-1,4)];
%      spotintable*1000
%      spot*1000
%    hightable = [hightable;addedrow];
%    hightable = sortrows(hightable,1);
%     next i
%     continue
%    end
%end


hightable;

longestdwelllow = max(lowtable(:,1));

%filler = [0:frame:longestdwelllow]';
% uniquedwells = unique(hightable(:,1)
%for i=1:1:(longestdwelllow*fps+1)
%     spot = filler(i);
%     spotintable = lowtable(i,1);
%spot = floor(filler(i)*1000);
%    spotintable = floor(lowtable(i,1)*1000);
%if spotintable == spot
      
 %       continue
 %   elseif spotintable > spot
 %   addedrow = [filler(i) 0 lowtable(i-1,3) lowtable(i-1,4)];
 %   lowtable = [lowtable;addedrow];
 %   lowtable = sortrows(lowtable,1);
%     next i
%     continue
  %  end
%end
% % % % % % % % % % % % % % % % % % % %     

%total length of dwells
timetotalhigh = sum(highsorted(:,2))/fps;    
timetotallow  = sum(lowsorted(:,2))/fps;

%number of dwells
totaldwellshigh = size(highsorted,1);
totaldwellslow = size(lowsorted,1);

%  Auto-generated by MATLAB on 23-Jun-2005 08:47:11
 title = [num2str(concentration) ' mM Metal kinetics' num2str(fps) ' fps'];
%% Create figure
%figure1 = figure('Color',[1 1 1],'Name', title,'PaperPosition',[0.25 0.25 8 10.5]);

figure1 = figure('Color',[1 1 1],'Name', title,'PaperPosition',[0 0 6 5],'papersize',[6 5]);
 
%% Create axes - High FRET dwells
axes1 = axes('FontName','Arial','FontSize',10,'Position',[0.1 0.55 0.4 .4],'Parent',figure1,'Visible','on','box','on');
axes3 = axes('FontName','Arial','FontSize',10,'Position',[0.3 0.55 0.22 .4],'Parent',figure1,'Visible','on','YAxisLocation','right','YColor','black','box','on');

%%Added Max 112707 Want To Plot Residuals
axes5 = axes('FontName','Arial','FontSize',10,'Position',[0.1 0.3 0.4 0.2],'Parent',figure1,'Visible','on','box','on');
axes6 = axes('FontName','Arial','FontSize',10,'Position',[0.3 0.3 0.22 0.2],'Parent',figure1,'Visible','on','YAxisLocation','right','YColor','black','box','on');
%%End Added Max 112707 Want To Plot Residuals



ylim(axes1,[0 1.1]);
ylim(axes3,[0 1.1]);

set(axes3,'YTick', []);
set(axes6,'YTick', []);

%xlabel(axes1,'Dwell time (s)');
ylabel(axes1,'Normalized counts (cumulative)');
hold(axes1,'all');
hold(axes3,'all');
 
%%Added Max 112707 Want To Plot Residuals
ylim(axes5,[-0.2 0.2]);
ylim(axes6,[-0.2 0.2]);
xlabel(axes5,'Dwell time (s)');
ylabel(axes5,'Residuals');
hold(axes5,'all');
hold(axes6,'all');
%%End Added Max 112707 Want To Plot Residuals

%% Create scatter
scatter1 = scatter(hightable(:,1),hightable(:,4),'Parent',axes1,'Marker','square','MarkerEdgeColor',[0 0 0],'SizeData',[24],'DisplayName','unfoldingfast');
scatter3 = scatter(hightable(:,1),hightable(:,4),'Parent',axes3,'Marker','square','MarkerEdgeColor',[0 0 0],'SizeData',[24],'DisplayName','unfoldingslow');
  
%   fit with single and double exponenetials
                        options = optimset('LevenbergMarquardt','on','TolFun',0.0000000001,'MaxFunEvals',1000000,'TolX',1e-9,'MaxIter',1000,'Display','Final');
                        [doublefithigh, resnormhigh] = lsqcurvefit(@doubleexponential,[0.6,3,0.1],hightable(:,1),hightable(:,4),[0 0.001 0.001],[1 fps fps],options); %lsqcurvefit(@function,[GUESSES],xdata,ydata)
                        resnormhigh
                        doublefithighval = [doublefithigh 0];
                        doublefithighval(4) = doublefithigh(3);
                        doublefithighval(3) = (1-doublefithigh(1));
                        [singlefithigh resnormhighsingle]= lsqcurvefit(@singleexponential,[1],hightable(:,1),hightable(:,4));
                        resnormhighsingle
                        xvalues=hightable(:,1);
                        ydouble=(doubleexponential(doublefithigh,xvalues));
                        ysingle=(singleexponential(singlefithigh,xvalues));
                        
                        
%% Creats residuals
%%This cell was added by Max Greenfeld on 112707 To Plot Residuals

doubleresidual = hightable(:,4)-ydouble;
singleresidual = hightable(:,4)-ysingle;

%% Create plot double exponential
plot1 = plot(xvalues,ydouble,'Color',[0 0 1],'LineWidth',2,'Parent',axes1,'DisplayName','double exponential');
plot3 = plot(xvalues,ydouble,'Color',[0 0 1],'LineWidth',2,'Parent',axes3,'DisplayName','double exponential');
  
%% Create plot single exponential
plot2 = plot(xvalues,ysingle,'Color',[1 0 0],'LineWidth',2,'Parent',axes1,'DisplayName','single exponential');
plot4 = plot(xvalues,ysingle,'Color',[1 0 0],'LineWidth',2,'Parent',axes3,'DisplayName','single exponential');

%% Creat plot of residuals
%%This cell was added by Max Greenfeld on 112707 To Plot Residuals

plot5 = scatter(xvalues,doubleresidual,'Parent',axes5,'DisplayName','double exponential','Marker','square','MarkerEdgeColor',[0 0 1],'SizeData',[24]);
plot5a = scatter(xvalues,doubleresidual,'Parent',axes6,'DisplayName','double exponential','Marker','square','MarkerEdgeColor',[0 0 1],'SizeData',[24]);
plot6 = scatter(xvalues,singleresidual,'Parent',axes5,'DisplayName','single exponential','Marker','square','MarkerEdgeColor',[1 0 0],'SizeData',[24]);
plot6a = scatter(xvalues,singleresidual,'Parent',axes6,'DisplayName','single exponential','Marker','square','MarkerEdgeColor',[1 0 0],'SizeData',[24]);




%%
% Adjust x limits
% middley = find ((10*hightable(:,4)') <= 7.5);
middley = find ((10*hightable(:,4)') <= 7.5);  %not bad
middley=max(middley);

if middley <= 4
    middley = 4;
end
xaxisbreak = hightable(middley,1);
% set(axes1,'XTick'
xlim(axes1,[0 xaxisbreak]);
xlim(axes3,[xaxisbreak/2 longestdwellhigh+1]);
%adjusts tick marks and labels

% Redone by Max...I could not get the orrigional work
currentticks = get(axes1,'XTick');
for j=1:numel(currentticks)
    
    if currentticks(j) < xaxisbreak/2;
     newticks(j)= currentticks(j)
    end  
end
set(axes1,'XTick', newticks);

xlim(axes5,[0 xaxisbreak]);
xlim(axes6,[xaxisbreak/2 longestdwellhigh+1]);

currentticks = get(axes5,'XTick');
for j=1:numel(currentticks)
    
    if currentticks(j) < xaxisbreak/2;
     newticks(j)= currentticks(j)
    end  
end
set(axes5,'XTick', newticks);

betterticks =[xaxisbreak/2 get(axes3,'XTick')];
set(axes3,'XTick', betterticks);

betterticks =[xaxisbreak/2 get(axes6,'XTick')];
set(axes6,'XTick', betterticks);

%currentticks(1) = NaN;
%betterticks = [xaxisbreak currentticks];
%set(axes3,'XTick', betterticks,'XTickLabel', betterticks);


%
%t1=text(betterticks(1),0,'//','fontsize',15,'HorizontalAlignment','center');


%currentticks = get(axes3,'XTick');
% currentticks = [currentticks floor(max(hightable(end,1)))];
%currentticks(1) = NaN;
%betterticks = [xaxisbreak currentticks];
%set(axes3,'XTick', betterticks,'XTickLabel', betterticks);

% place Break
%t1=text(betterticks(1),0,'//','fontsize',15,'HorizontalAlignment','center');

%first point ticks
%currentticks = get(axes1,'XTick');
%betterticks = [currentticks(1);currentticks(2)];
%set(axes1,'XTick', betterticks, 'XTickLabel',betterticks);



% place Break
%t1=text(betterticks(1),0,'//','fontsize',15,'HorizontalAlignment','center');

%first point ticks
%currentticks = get(axes1,'XTick');
%betterticks = [currentticks(1);currentticks(2)];
%set(axes1,'XTick', betterticks, 'XTickLabel',betterticks);


% same code as previous code but but combins residuals plots 
% set(axes1,'XTick'
%adjusts tick marks and labels
%currentticks = get(axes6,'XTick');
%currentticks = [currentticks floor(max(hightable(end,1)))];
%currentticks(1) = NaN;
%betterticks = [xaxisbreak currentticks];
%set(axes6,'XTick', betterticks,'XTickLabel', betterticks);

% place Break
%t1=text(betterticks(1),0,'//','fontsize',15,'HorizontalAlignment','center');

%first point ticks
%currentticks = get(axes5,'XTick');
%betterticks = [currentticks(1);currentticks(2)];
%set(axes5,'XTick', betterticks, 'XTickLabel',betterticks);
% end same code as previous code but but combins residuals plots 

%% Create axes - Low FRET dwells
axes2 = axes('FontName','Arial','FontSize',10,'Position',[0.59 0.55 0.4 0.4],'Parent',figure1,'box','on');
axes4 = axes('FontName','Arial','FontSize',10,'Position',[0.78 0.55 0.22 0.4],'Parent',figure1,'Visible','on','YAxisLocation','right','YColor','black','box','on');

%%Added Max 112707 Want To Plot Residuals
axes7 = axes('FontName','Arial','FontSize',10,'Position',[0.59 0.3 0.4 0.2],'Parent',figure1,'box','on');
axes8 = axes('FontName','Arial','FontSize',10,'Position',[0.78 0.3 0.22 0.2],'Parent',figure1,'Visible','on','YAxisLocation','right','YColor','black','box','on');
%%End Added Max 112707 Want To Plot Residuals


set(axes4,'YTick', []);
set(axes8,'YTick', []);



ylim(axes2,[0 1.1]);
ylim(axes4,[0 1.1]);
%xlabel(axes2,'Dwell time (s)');
ylabel(axes2,'Normalized counts (cumulative)');
hold(axes2,'all');
hold(axes4,'all');



%%Added Max 112707 Want To Plot Residuals
ylim(axes7,[-0.2 0.2]);
ylim(axes8,[-0.2 0.2]);
xlabel(axes7,'Dwell time (s)');
ylabel(axes7,'Residuals');
hold(axes7,'all');
hold(axes8,'all');
%%End Added Max 112707 Want To Plot Residuals

 
%% Create scatter
scatter2 = scatter(lowtable(:,1),lowtable(:,4),'Parent',axes2,'Marker','o','SizeData',[24],'MarkerEdgeColor',[0 0 0],'DisplayName','foldingfast');
scatter4 = scatter(lowtable(:,1),lowtable(:,4),'Parent',axes4,'Marker','o','SizeData',[24],'MarkerEdgeColor',[0 0 0],'DisplayName','foldingslow');
 
%   fit with single and double exponenetials
                        options = optimset('LevenbergMarquardt','on','TolFun',0.0000000001,'MaxFunEvals',1000000,'MaxIter',1000,'Display','Final');
                        [doublefitlow, resnormlow, residuallow] = lsqcurvefit(@doubleexponential,[0.6,30,0.1],lowtable(:,1),lowtable(:,4),[0 .001 0.001],[1 fps fps],options);
                        resnormlow
                        residuallow;
                        doublefitlowval = [doublefitlow 0];
                        doublefitlowval(4) = doublefitlow(3);
                        doublefitlowval(3) = (1-doublefitlow(1));
                        [singlefitlow, resnormlowsingle] = lsqcurvefit(@singleexponential,[1],lowtable(:,1),lowtable(:,4));
                        resnormlowsingle
                        xvalues=lowtable(:,1);
                        ydouble=(doubleexponential(doublefitlow,xvalues));
                        ysingle=(singleexponential(singlefitlow,xvalues));
                    
%% Creats residuals
%%This cell was added by Max Greenfeld on 112707 To Plot Residuals

doubleresidual = lowtable(:,4)-ydouble;
singleresidual = lowtable(:,4)-ysingle;
                        
%% Create plot double exponential
plot1 = plot(xvalues,ydouble,'Color',[0 0 1],'LineWidth',2,'Parent',axes2,'DisplayName','double exponential');
plot3 = plot(xvalues,ydouble,'Color',[0 0 1],'LineWidth',2,'Parent',axes4,'DisplayName','double exponential');
 
%% Create plot single exponential
plot2 = plot(xvalues,ysingle,'Color',[1 0 0],'LineWidth',2,'Parent',axes2,'DisplayName','single  exponential');
plot4 = plot(xvalues,ysingle,'Color',[1 0 0],'LineWidth',2,'Parent',axes4,'DisplayName','single  exponential');


%% Creat plot of residuals
%%This cell was added by Max Greenfeld on 112707 To Plot Residuals

%plot7 = plot(xvalues,doubleresidual,'Color',[0 0 1],'LineWidth',2,'Parent',axes7,'DisplayName','double exponential');
%plot7a = plot(xvalues,doubleresidual,'Color',[0 0 1],'LineWidth',2,'Parent',axes8,'DisplayName','double exponential');
%plot8 = plot(xvalues,singleresidual,'Color',[1 0 0],'LineWidth',2,'Parent',axes7,'DisplayName','single exponential');
%plot8a = plot(xvalues,singleresidual,'Color',[1 0 0],'LineWidth',2,'Parent',axes8,'DisplayName','single exponential');



plot7 = scatter(xvalues,doubleresidual,'Parent',axes7,'DisplayName','double exponential','Marker','o','MarkerEdgeColor',[0 0 1],'SizeData',[24]);
plot7a = scatter(xvalues,doubleresidual,'Parent',axes8,'DisplayName','double exponential','Marker','o','MarkerEdgeColor',[0 0 1],'SizeData',[24]);
plot8 = scatter(xvalues,singleresidual,'Parent',axes7,'DisplayName','single exponential','Marker','o','MarkerEdgeColor',[1 0 0],'SizeData',[24]);
plot8a = scatter(xvalues,singleresidual,'Parent',axes8,'DisplayName','single exponential','Marker','o','MarkerEdgeColor',[1 0 0],'SizeData',[24]);



%% make it look nice
% Adjust x limits
middley = find ((10*lowtable(:,4)') <= 7.5);
middley=max(middley);

% set(axes1,'XTick'
if middley <= 4
    middley=4;
end
xaxisbreak = lowtable(middley,1);
xlim(axes2,[0 xaxisbreak]);
xlim(axes4,[xaxisbreak/2 longestdwelllow+1]);



currentticks = get(axes2,'XTick');
clear newticks
for j=1:numel(currentticks)
    
    if currentticks(j) < xaxisbreak/2;
     newticks(j)= currentticks(j)
    end  
end
set(axes2,'XTick', newticks);

xlim(axes7,[0 xaxisbreak]);
xlim(axes8,[xaxisbreak/2 longestdwelllow+1]);

currentticks = get(axes7,'XTick');
for j=1:numel(currentticks)
    
    if currentticks(j) < xaxisbreak/2;
     newticks(j)= currentticks(j)
    end  
end
set(axes7,'XTick', newticks);

betterticks =[xaxisbreak/2 get(axes3,'XTick')];
%set(axes4,'XTick', betterticks);

betterticks =[xaxisbreak/2 get(axes6,'XTick')];
%set(axes8,'XTick', betterticks);











%adjusts tick marks and labels
%currentticks = get(axes4,'XTick');
% currentticks(end) = floor(max(lowtable(end,1)));
%currentticks(1) = NaN;
%betterticks = [xaxisbreak currentticks] 
%set(axes4,'XTick', betterticks,'XTickLabel', betterticks);

% place Break
%t1=text(betterticks(1),0,'//','fontsize',15,'HorizontalAlignment','center');

%first point ticks
%currentticks = get(axes2,'XTick');
%betterticks = [currentticks(1);currentticks(2)];
%set(axes2,'XTick', betterticks, 'XTickLabel',betterticks);

% same code as previous code but but combins residuals plots 
% set(axes1,'XTick'
%xlim(axes7,[0 xaxisbreak]);
%xlim(axes8,[xaxisbreak/2 longestdwelllow+1]);
%adjusts tick marks and labels
%currentticks = get(axes8,'XTick');
%currentticks = [currentticks floor(max(hightable(end,1)))];
%currentticks(1) = NaN;
%betterticks = [xaxisbreak currentticks];
%set(axes8,'XTick', betterticks,'XTickLabel', betterticks);

% place Break
%t1=text(betterticks(1),0,'//','fontsize',15,'HorizontalAlignment','center');

%first point ticks
%currentticks = get(axes7,'XTick');
%betterticks = [currentticks(1);currentticks(2)];
%set(axes7,'XTick', betterticks, 'XTickLabel',betterticks);
% end same code as previous code but but combins residuals plots 



%% Create legend
%legend1 = legend(axes1,{'unfolding','double exponential','single exponential'},'FontName','Arial','FontSize',10,'Position',[0.25 0.15 0.2 0.1]);
 
%% Create legend
%legend2 = legend(axes2,{'folding','double exponential','single exponential'},'FontName','Arial','FontSize',10,'Position',[0.73 0.15 0.2 0.1]);

%create annotation labels
a = ['k = ' num2str(round(100*singlefithigh)/100)];
b = ['A1 = ' num2str(round(100*doublefithighval(1))/100)];
c = ['k1 = ' num2str(round(100*doublefithighval(2))/100)];
d = ['A2 = ' num2str(round(100*doublefithighval(3))/100)];
e = ['k2 = ' num2str(round(100*doublefithighval(4))/100)];
f = [num2str(timetotalhigh) ' s'];
g = [num2str(totaldwellshigh) ' dwells'];
h = ['# Molecules = ' num2str(numbermolecules)];


%% Create textbox
annotation1 = annotation(figure1,'textbox','Position',[0.1 0.1 0.1 0.1],'FitHeightToText','on','String',{a,b,c,d,e,},'LineStyle','none');
annotation3 = annotation(figure1,'textbox','Position',[0.25 0.1 0.1 0.1],'FitHeightToText','on','String',{f,g,h},'LineStyle','none');
annotation5 = annotation(figure1,'textbox','Position',[0.15 0.7 0.3 0.3],'String','Unfolding','LineStyle','None','FontSize',18);    

%create annotation labels
a = ['k = ' num2str(round(100*singlefitlow)/100)];
b = ['A1 = ' num2str(round(100*doublefitlowval(1))/100)];
c = ['k1 = ' num2str(round(100*doublefitlowval(2))/100)];
d = ['A2 = ' num2str(round(100*doublefitlowval(3))/100)];
e = ['k2 = ' num2str(round(100*doublefitlowval(4))/100)];
f = [num2str(timetotallow) ' s'];
g = [num2str(totaldwellslow) ' dwells'];
h = ['# Molecules = ' num2str(numbermolecules)];

%% Create textbox
annotation2 = annotation(figure1,'textbox','Position',[0.59 0.1 0.1 0.1],'FitHeightToText','on','String',{a,b c,d e},'LineStyle','none');
annotation4 = annotation(figure1,'textbox','Position',[0.79 0.1 0.1 0.1],'FitHeightToText','on','String',{f,g,h},'LineStyle','none');
annotation6 = annotation(figure1,'textbox','Position',[0.65 0.7 0.3 0.3],'String','Folding','LineStyle','None','FontSize',18);  
%output answer

output = [concentration, singlefithigh doublefithighval, singlefitlow doublefitlowval timetotalhigh totaldwellshigh timetotallow totaldwellslow ];



% % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % 
% % OLD CODE
% % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % 

% % %% Create scatter
% % scatter2 = scatter(lowtable(:,1),lowtable(:,4)
% %   'Parent',axes2,...
% %   'DisplayName','b vs. a',...
% %   'XDataSource','a',...
% %   'YDataSource','b');
   
    
% %                             % plot the data
% %                         figure
% %                         scatter(hightable(:,1),hightable(:,4))
% %                         % fit with single and double exponenetials
% %                         options = optimset('LevenbergMarquardt','on');
% %                         doublefithigh = lsqcurvefit(@doubleexponential,[1,3,1,1],hightable(:,1),hightable(:,4));
% %                         singlefithigh = lsqcurvefit(@singleexponential,[1],hightable(:,1),hightable(:,4));
% %                         xvalues=hightable(:,1);
% %                         hold all
% %                         ydouble=(doubleexponential(doublefithigh,xvalues));
% %                         ysingle=(singleexponential(singlefithigh,xvalues));
% %                         plot(xvalues,ydouble)
% %                         plot(xvalues,ysingle)
% %                         %give the axis labels, and graph a title, and a legend, diplay the fits
% % 
% % 
% %                         % plot the data
% %                         figure
% %                         scatter(lowtable(:,1),lowtable(:,4))
% %                         % fit with single and double exponenetials
% %                         options = optimset('LevenbergMarquardt','on');
% %                         doublefitlow = lsqcurvefit(@doubleexponential,[1,3,1,1],lowtable(:,1),lowtable(:,4));
% %                         singlefitlow = lsqcurvefit(@singleexponential,[1],lowtable(:,1),lowtable(:,4));
% %                         xvalues=lowtable(:,1);
% %                         hold all
% %                         ydouble=(doubleexponential(doublefitlow,xvalues));
% %                         ysingle=(singleexponential(singlefitlow,xvalues));
% %                         plot(xvalues,ydouble)
% %                         plot(xvalues,ysingle)
% %                         %give the axis labels, and graph a title, and a legend, diplay the fits
% % 
