% GT65X_INIT  Initialize GT658 counter card
%     errorcode = gt65x_init(ixBoard) initializes the card
%     with board index (ixBoard) and returns any error code
%     generated by the driver (or 0 for a success).

function errorcode = gt65x_init(ixBoard),

if nargin < 1,
	error('Board index required!');
end;

if ixBoard ~= 1 & ixBoard ~= 0,
	error('Invalid board index!');
end;

errorcode = gt65x_init_mex(ixBoard);

return;
